name: Deploy

on:
  push:
    branches: 
      - 'main'
    paths:
      - '**'
      - '!.gitignore'
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!LICENSE'
  pull_request:
    branches: ["main"]
  
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true


jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependancies
        run: npm ci
      
      - name: Start Linters
        run: npm run lint:all  
      
      - name: Run all scripts
        run: |
          for script in *.js; do
            node "$script"
          done

      - name: test
        run: node url-checker.js -t ${{ vars.URL_CHECKER_TIMEOUT }} -p 'src/posts'
        env:
          URL_CHECKER_TIMEOUT: ${{ vars.URL_CHECKER_TIMEOUT }}


  build:
    name: build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup pages
        uses: actions/configure-pages@v4
      
      - name: setup node
        uses: actions/setup-node@v4
        with:
          version: '18'
          cache: 'npm'
      
      - name: build site
        run: num run prod
        env:
          PATH_PREFIX : /github-actions-project/
      
      - name: upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site
  
  deploy:
    name: deploy
    needs: [build, test]
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write
      issues: write

    steps:
      - name: deploy pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Create Success Issue
        if: success()  
        run: |
          gh issue create \
            --title "$(date+'%Y-%m-%d') -Deployement:succeeded" \
            --body "URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Failure Issue
        if: failure()
        run: |
          gh issue create \
          --title "$(date +'%Y-%m-%d') - Deployment: failed" \
          --body "URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



